# Book Name:

   * Python for Data Analysis
   
   
  <img src='https://bukharibooks.com/wp-content/uploads/2021/05/pythondataanylysis.png'>

# Chapter Number:

   * 4
   
   
# Chapter Name:
   
   * NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np
my_arr = np.arange(1000000)

In [2]:
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 66 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 1.98 s
Wall time: 2.7 s


# 4.1 The NumPy ndarray: 

A Multidimensional Array Object


In [5]:
data = np.random.randn(2, 3)
data

array([[-0.07057253, -2.24269412,  0.23677261],
       [ 0.8722621 ,  1.66329957,  0.64299536]])

In [6]:
data * 10

array([[ -0.70572526, -22.42694119,   2.36772611],
       [  8.72262098,  16.6329957 ,   6.42995359]])

In [7]:
data + data

array([[-0.14114505, -4.48538824,  0.47354522],
       [ 1.7445242 ,  3.32659914,  1.28599072]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2, 3, 2))

array([[[1.04916766e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 7.12313140e-067]],

       [[1.53351175e-075, 6.23010745e-038],
        [7.93287423e+165, 1.11580092e-046],
        [1.46202397e+185, 2.57112122e+184]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<img src='https://raw.githubusercontent.com/AbdullahJaffrey/SaylaniAssignments/master/NumPyAssignment/Numpy1.png?token=GHSAT0AAAAAABYYDVRGCVAE3O2SANLTIKRUYZB4SOQ'>

# Data Types for ndarrays
The data type or dtype is a special object containing the information (or metadata,
data about data) the ndarray needs to interpret a chunk of memory as a particular
type of data:


<img src = 'https://raw.githubusercontent.com/AbdullahJaffrey/SaylaniAssignments/master/NumPyAssignment/Numpy2.png?token=GHSAT0AAAAAABYYDVRGCVAE3O2SANLTIKRUYZB4SOQ'>

In [22]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
float_arr = arr2.astype(np.float64)

In [25]:
float_arr

array([1., 2., 3.])

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [27]:
 arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [28]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [29]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [30]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [31]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [32]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [34]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

# Arithmetic with NumPy Arrays:

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [37]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [40]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [44]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [45]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing:

<img src = 'Numpy3.png'>

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5]

5

In [48]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [49]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [52]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# Slicing For 2d array:

In [53]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [54]:
arr2[1, 1]

2.0

In [55]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[2]

array([7, 8, 9])

In [57]:
arr2d[0][2]

3

In [58]:
arr2d[0, 2]

3

# Slicing For 3d array:

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[1, 0]

array([7, 8, 9])

In [65]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [66]:
x[0]

array([7, 8, 9])

# Indexing with slices:

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [69]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [72]:
arr2d[1, :2]

array([4, 5])

In [73]:
arr2d[:2, 2]

array([3, 6])

In [74]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [75]:
arr2d[:2, 1:] = 0

In [76]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

<img src = 'Numpy4.png'>

In [77]:
#Done